/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsIndexRouteImport } from './routes/assignments.index'
import { Route as AssignmentsOutputRouteImport } from './routes/assignments.output'
import { Route as AssignmentsNewRouteImport } from './routes/assignments.new'

const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsIndexRoute = AssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsOutputRoute = AssignmentsOutputRouteImport.update({
  id: '/assignments/output',
  path: '/assignments/output',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsNewRoute = AssignmentsNewRouteImport.update({
  id: '/assignments/new',
  path: '/assignments/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/toolkit': typeof ToolkitRoute
  '/assignments/new': typeof AssignmentsNewRoute
  '/assignments/output': typeof AssignmentsOutputRoute
  '/assignments/': typeof AssignmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/toolkit': typeof ToolkitRoute
  '/assignments/new': typeof AssignmentsNewRoute
  '/assignments/output': typeof AssignmentsOutputRoute
  '/assignments': typeof AssignmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/toolkit': typeof ToolkitRoute
  '/assignments/new': typeof AssignmentsNewRoute
  '/assignments/output': typeof AssignmentsOutputRoute
  '/assignments/': typeof AssignmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/library'
    | '/settings'
    | '/toolkit'
    | '/assignments/new'
    | '/assignments/output'
    | '/assignments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/library'
    | '/settings'
    | '/toolkit'
    | '/assignments/new'
    | '/assignments/output'
    | '/assignments'
  id:
    | '__root__'
    | '/'
    | '/groups'
    | '/library'
    | '/settings'
    | '/toolkit'
    | '/assignments/new'
    | '/assignments/output'
    | '/assignments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsRoute: typeof GroupsRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  ToolkitRoute: typeof ToolkitRoute
  AssignmentsNewRoute: typeof AssignmentsNewRoute
  AssignmentsOutputRoute: typeof AssignmentsOutputRoute
  AssignmentsIndexRoute: typeof AssignmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/': {
      id: '/assignments/'
      path: '/assignments'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/output': {
      id: '/assignments/output'
      path: '/assignments/output'
      fullPath: '/assignments/output'
      preLoaderRoute: typeof AssignmentsOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/new': {
      id: '/assignments/new'
      path: '/assignments/new'
      fullPath: '/assignments/new'
      preLoaderRoute: typeof AssignmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsRoute: GroupsRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  ToolkitRoute: ToolkitRoute,
  AssignmentsNewRoute: AssignmentsNewRoute,
  AssignmentsOutputRoute: AssignmentsOutputRoute,
  AssignmentsIndexRoute: AssignmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
